FROM node:20 AS build

WORKDIR /app/webpartytime

COPY webpartytime/package*.json ./

RUN npm install

COPY webpartytime .

RUN npm run build

FROM docker.io/library/nginx:stable as production

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/webpartytime/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]